songs = [
    "I ​/ ​Me ​/ ​Myself by Will Wood",
    "Suburbia Overture / Greetings from Mary Bell Township! / (Vampire) Culture / Love Me, Normally by Will Wood",
    "BlackBoxWarrior - OKULTRA by Will Wood",
    "Dr. Sunshine is Dead by Will Wood and the Tapeworms",
    "2econd​-2ight​-2eer (that was fun, goodbye​.​) by Will Wood",
    "Laplace’s Angel (Hurt People? Hurt People!) by Will Wood",
    "Thermodynamic Lawyer, Esq, G.F.D. by Will Wood and the Tapeworms",
    "The Song with Five Names, a​.​k​.​a. Soapbox Tao, a​.​k​.​a. Checkmate Atheists! a​.​k​.​a. Neospace Government, a​.​k​.​a. You Can Never Know by Will Wood and the Tapeworms",
    "6up 5oh Cop-Out (Pro / Con) by Will Wood and the Tapeworms",
    "Mr. Capgras Encounters a Secondhand Vanity: Tulpamancer’s Prosopagnosia/Pareidolia (As Direct Result of Trauma to the Fusiform Gyrus) by Will Wood and the Tapeworms",
    "Marsha, Thankk You for the Dialectics, but I Need You to Leave. by Will Wood",
    "Front Street by Will Wood and the Tapeworms",
    "Hand Me My Shovel, I’m Going In! by Will Wood and the Tapeworms",
    "Skeleton Appreciation Day in Vestal, NY (Bones) by Will Wood and the Tapeworms",
    "Love, Me Normally by Will Wood",
    "Cotard’s Solution (Anatta​/​Dukkha​/​Anicca) by Will Wood and the Tapeworms",
    "...well, better than the alternative by Will Wood",
    "Outliars and Hyppocrates: a fun fact about apples by Will Wood",
    "The Main Character by Will Wood",
    "Against the Kitchen Floor by Will Wood",
    "2012 by Will Wood and the Tapeworms",
    "Chemical Overreaction / Compound Fracture by Will Wood and the Tapeworms",
    "Tomcat Disposables by Will Wood",
    "Cicada Days by Will Wood",
    "Memento Mori: the most important thing in the world by Will Wood",
    "The First Step by Will Wood and the Tapeworms",
    "Willard! by Will Wood",
    "White Knuckle Jerk (Where Do You Get Off?) by Will Wood and the Tapeworms",
    "Your Body, My Temple by Will Wood",
    "¡Aikido! (Neurotic/Erotic) by Will Wood and the Tapeworms",
    "Euthanasia by Will Wood",
    "Love Me Normally (2016 Live Demo) by Will Wood and the Tapeworms",
    "White Noise by Will Wood",
    "That’s Enough, Let’s Get You Home. by Will Wood",
    "Yes, to Err is Human, So Don’t Be One. (Song) by Will Wood",
    "Big Fat Bitchie’s Blueberry Pie, Christmas Tree, and Recreational Jell-o Emporium a.k.a. 'Mr. Boy is on the Roof Again' (Feat. Pasta by Sneakers McSqueakers) [From 'B.F.B.’s B-Sides: Bagel Batches, Marsh-Mallows, & Barsh-Mallows'] by Will Wood",
    "Becoming the Lastnames by Will Wood",
    "RED MOON by Will Wood and the Tapeworms",
    "Um, It’s Kind of a Lot by Will Wood",
    "Vampire Reference in a Minor Key by Will Wood",
    "Sex, Drugs, Rock ‘n’ Roll by Will Wood",
    "Falling Up by Will Wood",
    "Lysergide Daydream by Will Wood and the Tapeworms",
    "Everything is a lot. by Will Wood and the Tapeworms",
    "(Cover This Song) A Little Bit Mine by Will Wood and the Tapeworms",
    "Self- by Will Wood and the Tapeworms",
    "Jimmy Mushrooms’ Last Drink: Bedtime in Wayne, NJ by Will Wood and the Tapeworms",
    "Misanthrapologist (”In case I make it,” Outtake) - Live in Backroom Studios, Rockaway, NJ by Will Wood",
    "When Somebody Needs You by Will Wood",
    "-ish by Will Wood and the Tapeworms",
    "Half-Decade Hangover by Will Wood",
    "You Liked This (Okay, Computer!) by Will Wood",
    "...And If I Did, You Deserved It. (”In case I make it,” Outtake) - Live at Knitting Factory, Spokane, WA by Will Wood",
    "Venetian Blind Man (Song) by Will Wood",
    "Destroy by Will Wood and the Tapeworms",
    "He’ll Use Me For His Needle Show by A Verbal Equinox",
    "1fish2fish by The Stereosexuals",
    "Destroy to Enjoy (Remastered) by Will Wood and the Tapeworms",
    "¡Nüburbåtizé! by A Verbal Equinox",
    "Cut/Clap by The Stereosexuals",
    "The Song with Five Names a.k.a. Soapbox Tao a.k.a. Checkmate Atheists! a.k.a. Neospace Government a.k.a. You Can Never Know (Remastered) by Will Wood and the Tapeworms",
    "Bleüctipie by A Verbal Equinox",
    "Thermodynamic Lawyer, Esq, G.F.D. (Remastered) by Will Wood and the Tapeworms",
    "The First Step (Remastered) by Will Wood and the Tapeworms",
    "The Better To Eat You With (ft. Michael Hovsepian) by The Stereosexuals",
    "Wealth and Hellness by Human Zoo",
    "Skeleton Appreciation Day in Vestal, NY (Bones) [Remastered] by Will Wood and the Tapeworms",
    "Front Street (Remastered) by Will Wood and the Tapeworms",
    "Welcome to Camp Here & There by Will Wood",
    "Hand Me My Shovel, I’m Going In! (Remastered) by Will Wood and the Tapeworms",
    "Man, I Love Being Drunk (Live at Music Inn 2015) by Will Wood",
    "Laplace’s Angel (Hurt People? Hurt People!) by Chonny Jash",
    "6up 5oh Cop-Out (Pro/Con) [Remastered] by Will Wood and the Tapeworms",
    "Drugs Ain’t Cheap In Poughkeepsie by A Verbal Equinox",
    "The Rhumba of Death by Will Wood",
    "(Cover This Song!) A Little Bit Mine [Remastered] by Will Wood and the Tapeworms",
    "Alma Mater by Will Wood",
    "Chemical Overreaction / Compound Fracture (Remastered) by Will Wood and the Tapeworms",
    "¡Aikido! (Neurotic/Erotic) [Remastered] by Will Wood and the Tapeworms",
    "Mr. Capgras Encounters a Secondhand Vanity: Tulpamancer’s Prosopagnosia​/​Pareidolia (As Direct Result of Trauma to the Fusiform Gyrus) [Remastered] by Will Wood and the Tapeworms",
    "Thermodynamic Lawyer Esq, G.F.D. by Chonny Jash",
    "Sing the Singer/Songwriter Song by A Verbal Equinox",
    "2012 (Remastered) by Will Wood and the Tapeworms",
    "We Killed Amanda Palmer, Mystery Solved by A Verbal Equinox",
    "10-4 6-up 5-Oh Cop-out Pro-Con - Live by Will Wood and the Tapeworms",
    "DUI in the Sky by A Verbal Equinox",
    "Under a Technicolor Sky by Will Wood",
    "Yes, to Err is Human, So Don’t Be One. [Instrumental] by Will Wood",
    "Thermodynamic Lawyer - Live by Will Wood and the Tapeworms",
    "Everything Is A Lot (Remastered) by Will Wood and the Tapeworms",
    "Dr. Sunshine is Dead (Remastered) by Will Wood and the Tapeworms",
    "Black Box Warrant (Bonus) [Live] by Will Wood and the Tapeworms",
    "Your Body, My Temple [Instrumental] by Will Wood",
    "Fibrodysplasia Ossificans Progressiva - Live by Will Wood and the Tapeworms",
    "The Song With 5 Names - Live at The Foundry, Lakewood, OH by Will Wood",
    "Red Moon (Remastered) by Will Wood and the Tapeworms",
    "Dr. Sunshine Lives! - Live by Will Wood and the Tapeworms",
    "Lysergide Daydream (Remastered) by Will Wood and the Tapeworms",
    "Cotard’s Solution [Kill Me?] - Live by Will Wood and the Tapeworms",
    "White Knuckle Jerk (Where Do You Get Off?) [Remastered] by Will Wood and the Tapeworms",
    "Front Street - Live by Will Wood and the Tapeworms",
    "White Noise - Live at The Vermont Hollywood, Los Angeles, CA by Will Wood",
    "Good Morning, Campers! by Will Wood",
    "Wasting Away Again in Bupropionville - Live by Will Wood and the Tapeworms",
    "Self- (Remastered) by Will Wood and the Tapeworms",
    "Under a Monochromatic Sky by Will Wood",
    "Zen Master by Jamface",
    "Hand Me My [X] I’m [Y]! - Live by Will Wood and the Tapeworms",
    "Jimmy Mushrooms’ Last Drink: Bedtime in Wayne, N.J. (Remastered) by Will Wood and the Tapeworms",
    "Heathers Big Break by Jamface",
    "Mr. Capgras - Live by Will Wood and the Tapeworms",
    "Recurring Nightmare #432 by A Verbal Equinox",
    "Morning Announcements by Will Wood",
    "You Are Love by Will Wood",
    "Where Do You Get Off? - Live by Will Wood and the Tapeworms",
    "Venetian Blind Man [Instrumental] by Will Wood",
    "-Ish (Remastered) by Will Wood and the Tapeworms",
    "Pronoia by Strange Thick",
    "Hey by Big Ears Glenn",
    "“Nobody” (Untitled) by Will Wood",
    "Bob Zmuda v. James Carrey (Live) by Will Wood and the Tapeworms",
    "Prince Ali (Aladdin) by Will Wood and the Land Pirates",
    "Tomcat Disposables by Chonny Jash",
    "I / Me / Myself - Live at City Winery, Atlanta, GA by Will Wood",
    "Afternoon Announcements by Will Wood",
    "Chemical Overreaction - Live by Will Wood and the Tapeworms",
    "…And If I Did, You Deserved It. by Chonny Jash",
    "Against the Kitchen Floor - Live in Charlotte, NC by Will Wood",
    "Cicada Days - Live at Knitting Factory, Spokane, WA by Will Wood",
    "Gilded Cog by Jamface",
    "Memento Mori: the most important thing in the world by Chonny Jash",
    "Evening Announcements by Will Wood",
    "Aphrodite, Your Electric Sexiness by Human Zoo",
    "Laplace’s Angel - Live at Blueberry Hill Duck Room, St. Louis, MO by Will Wood",
    "Skeleton Appreciation Day - Live at Ace of Cups, Columbus, OH by Will Wood",
    "The Main Character - Live at The Vermont Hollywood, Los Angeles, CA by Will Wood",
    "The First Step - Live at The Bitter End, New York, NY by Will Wood",
    "That’s Enough, Let’s Get You Home - Live in Backroom Studios, Rockaway, NJ by Will Wood",
    "Outliars And Overreactions (The Song With One Name) by Jayden Wark",
    "2012 - Live by Will Wood and the Tapeworms",
    "Millie Rolls a 7 (Bonus) [Live] by Will Wood and the Tapeworms",
    "Jimmy Mushrooms’ Last Drink - Live at Austin City Limits, Austin, TX by Will Wood",
    "Red Moon (Live) by Will Wood and the Tapeworms",
    "Mike (Live) by Will Wood and the Tapeworms",
    "Aikido - Live by Will Wood and the Tapeworms",
    "Self- - Live by Will Wood and the Tapeworms",
    "The First Step - Live by Will Wood and the Tapeworms",
    "Love, Me Normally - Live at Hawthorne Theater, Portland, OR by Will Wood",
    "Becoming the Lastnames - Live at City Winery, Nashville, TN by Will Wood",
    "Man, I Love Being Drunk by Will Wood",
    "Love Me Normally (Bonus) [Live] by Will Wood and the Tapeworms",
    "Vampire Reference in a Minor Key - Live at World Café Live, Philadelphia, PA by Will Wood",
    "Front Street (Live at The Haus 2016) by Will Wood and the Tapeworms",
    "Euthanasia - Live at Hawthorne Theater, Portland, OR by Will Wood",
    "Well, Better Than The Dialectics, But I Prefer You Use I/Me/Myself (Normal Album Cover And Mashup) by Jayden Wark",
    "Falling Up - Live in Backroom Studios, Rockaway, NJ by Will Wood",
    "Half-Decade Hangover - Live at City Winery, Atlanta, GA by Will Wood",
    "The Velocity of Love by Will Wood",
    "Credits (EIAT Version) by Will Wood and the Tapeworms",
    "-ish - Live by Will Wood and the Tapeworms",
    "Whoopi Goldberg Was A Mistake by A Verbal Equinox",
    "Tomcat Disposables - Live at Nectar Lounge, Seattle, WA by Will Wood",
    "In the Night Time (Live at Jammin’ TV) by Strange Thick",
    "Hindsight Glasses 20/20 (Live Recording Canvas Clash) by Strange Thick",
    "Chocolate Jesus (Tom Waits Cover) by Will Wood",
    "Armchairs (Andrew Bird Cover) by Will Wood",
    "Credits (Self-Ish Version) by Will Wood and the Tapeworms",
    "NowHere by Jamface",
    "Dr. Sunshine is Dead (Live) (From Going The Distance Volume 2) by Will Wood",
    "Credits (TRWW Version) by Will Wood and the Tapeworms",
    "(Cover This Song) A Little Bit Mine by Josh Greer",
    "In the Nighttime (Live Recording Canvas Clash) by Strange Thick",
    "Jane Doe by Callout",
    "White Knuckle Jerk (live at Antifolk 2015) by Will Wood",
    "Sauce (’Cause I Put it There) (Studio Version) by Strange Thick",
    "Ryan I Wonder (Live) by Will Wood",
    "Will Wood - Against the Kitchen Floor (پشتو تورجمانی) by Genius Pashto Translations",
    "Shining Star by Jamface",
    "Man, I Love Being Drunk (Live at Sidewalk 2015) by Will Wood",
    "Self-Ish (Live @ HEAD 2019) by Will Wood",
    "He’ll Use Me For His Needle Show (Demo) by A Verbal Equinox"
]